
import { Category, UserSettings } from './types';

// =========================================================================
// 🚀 DEPLOYMENT CONFIGURATION (部署配置)
// Fill in your Supabase credentials here before deploying.
// 在此处填写您的 Supabase URL 和 Anon Key
// =========================================================================
export const SUPABASE_CONFIG = {
  url: "https://trvyydvygcthtagztiii.supabase.co", // e.g., "https://xyz.supabase.co"
  key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRydnl5ZHZ5Z2N0aHRhZ3p0aWlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ3OTI5MjUsImV4cCI6MjA4MDM2ODkyNX0.vxfbxoim8-ymX5OF4_JJFI2jY0ZYyn4EsZ9FJWPbv4I"  // e.g., "eyJhbGciOiJIUzI1NiIsInR5cCI6..." (Anon Public Key)
};

export const DEFAULT_CATEGORIES: Category[] = [];

export const DEFAULT_SETTINGS: UserSettings = {
  username: 'Admin',
  baseCurrency: 'CNY',
  ratesUpdatedAt: '',
  themeColor: '#3b82f6', // Tailwind blue-500
  darkMode: false,
  language: 'zh',
  notificationStyle: 'simple',
  defaultNotifyDays: 3,
  currencyRates: {
    CNY: 1,
    USD: 0.14,
    EUR: 0.13,
    GBP: 0.11,
    JPY: 20.5,
  }
};

// Curated list of 18 essential icons to fit without scrolling
export const ICONS = [
  'Zap', 'Music', 'Video', 'Cloud', 'Gamepad', 'Book',
  'Briefcase', 'Coffee', 'Globe', 'Home', 'Smartphone', 'ShoppingBag',
  'Wifi', 'CreditCard', 'Shield', 'Smile', 'Star', 'Headphones'
];

export const TRANSLATIONS = {
  zh: {
    dashboard: '仪表盘',
    subscriptions: '订阅管理',
    settings: '设置',
    monthlyCost: '月度支出',
    yearlyCost: '年度支出',
    activeSubs: '活跃订阅',
    upcomingRenewals: '即将续费',
    recentActivity: '最近添加',
    notificationLog: '通知日志',
    addSubscription: '添加订阅',
    editSubscription: '编辑订阅',
    name: '名称',
    price: '价格',
    currency: '货币',
    cycle: '周期',
    weekly: '每周',
    monthly: '每月',
    quarterly: '每季',
    yearly: '每年',
    category: '分类',
    description: '描述 / 备注',
    nextPaymentDate: '下一次扣费日期',
    notify: '提醒设置',
    daysBefore: '提前通知 (天)',
    save: '保存',
    cancel: '取消',
    delete: '删除',
    renew: '一键续费',
    renewTitle: '手动续费',
    renewDesc: '将下一次扣费日期向后推迟一个周期',
    confirmRenew: '确认续费',
    search: '搜索...',
    theme: '外观',
    darkMode: '深色模式',
    lightMode: '浅色模式',
    primaryColor: '主题色',
    dataManagement: '数据管理',
    exportData: '导出数据 (JSON)',
    importData: '导入数据',
    telegramSettings: 'Telegram 通知',
    botToken: 'Bot Token',
    chatId: 'Chat ID',
    sendTest: '发送测试消息',
    days: '天',
    today: '今天',
    tomorrow: '明天',
    costDistribution: '支出分布',
    createNewCategory: '创建新分类',
    categoryName: '分类名称',
    color: '颜色',
    login: '登录',
    register: '注册账号',
    welcome: '欢迎回来',
    logout: '退出登录',
    noSubscriptions: '暂无订阅，点击上方按钮添加',
    confirmDelete: '确定要删除这个订阅吗？',
    language: '语言 / Language',
    accountSecurity: '账号安全',
    changeUsername: '修改用户名',
    changePassword: '修改密码',
    newPassword: '新密码',
    currentPassword: '当前密码',
    update: '更新',
    notificationStyle: '通知样式',
    simple: '简洁',
    detailed: '详细',
    defaultNotifyDays: '默认提醒天数',
    pleaseFillRequired: '请填写所有必填项 (名称, 价格, 分类)',
    accountCreated: '账号创建成功，请登录',
    userExists: '用户名已存在',
    loginFailed: '用户名或密码错误',
    passwordUpdated: '密码已更新',
    usernameUpdated: '用户名已更新',
    uncategorized: '未分类',
    remaining: '剩余',
    dataSync: '云端同步',
    syncDesc: '同步数据到云端数据库 (Supabase)',
    syncNow: '立即同步',
    syncSuccess: '同步成功!',
    syncError: '同步失败 (请检查 constants.ts 配置)',
    notConfigured: '数据库未配置',
    baseCurrency: '基准货币',
    currencyRatesLabel: '汇率',
    refreshRates: '刷新汇率',
    lastUpdated: '上次更新时间',
    manualRefresh: '手动更新',
    rateFetchFailed: '汇率更新失败',
    categoryManagement: '分类管理',
    addCategory: '新增分类',
    editCategory: '编辑分类',
    colorPresets: '推荐色彩',
    calendarView: '订阅日历',
    spendingTrends: '支出趋势',
    budgetSettings: '预算设置',
    monthlyBudgetLimit: '每月预算限额',
    emailNotifications: '邮件通知 (SMTP)',
    enableEmail: '启用邮件通知',
    smtpServer: 'SMTP 服务器',
    smtpPort: 'SMTP 端口',
    smtpUser: 'SMTP 用户名',
    smtpPassword: 'SMTP 密码',
    fromEmail: '发件人邮箱',
    monthlyBudget: '月度预算',
    spent: '已支出',
    budgetExceeded: '您已超出月度预算！',
    tags: '标签 (逗号分隔)',
    chooseIcon: '选择图标',
    tagsPlaceholder: '例如：软件, 工作, 娱乐',
    budgetDesc: '设置每月支出限额，当超出时在仪表盘显示警告。',
    chooseColor: '选择颜色',
    smtpDesc: '配置自定义 SMTP 服务器以发送邮件通知。',
    sendTestEmail: '发送测试邮件',
    emailEnabled: '邮件通知已启用',
    emailDisabled: '邮件通知未启用',
  },
  en: {
    dashboard: 'Dashboard',
    subscriptions: 'Subscriptions',
    settings: 'Settings',
    monthlyCost: 'Monthly Cost',
    yearlyCost: 'Yearly Cost',
    activeSubs: 'Active Subs',
    upcomingRenewals: 'Upcoming Renewals',
    recentActivity: 'Recently Added',
    notificationLog: 'Notification Log',
    addSubscription: 'Add Subscription',
    editSubscription: 'Edit Subscription',
    name: 'Name',
    price: 'Price',
    currency: 'Currency',
    cycle: 'Billing Cycle',
    weekly: 'Weekly',
    monthly: 'Monthly',
    quarterly: 'Quarterly',
    yearly: 'Yearly',
    category: 'Category',
    description: 'Description',
    nextPaymentDate: 'Next Payment Date',
    notify: 'Notification',
    daysBefore: 'Days Before',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    renew: 'Renew',
    renewTitle: 'Quick Renew',
    renewDesc: 'Extend the next payment date by one cycle',
    confirmRenew: 'Confirm Renew',
    search: 'Search...',
    theme: 'Appearance',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    primaryColor: 'Primary Color',
    dataManagement: 'Data Management',
    exportData: 'Export Data (JSON)',
    importData: 'Import Data',
    telegramSettings: 'Telegram Notification',
    botToken: 'Bot Token',
    chatId: 'Chat ID',
    sendTest: 'Send Test Message',
    days: 'days',
    today: 'Today',
    tomorrow: 'Tomorrow',
    costDistribution: 'Cost Distribution',
    createNewCategory: 'Create New Category',
    categoryName: 'Category Name',
    color: 'Color',
    login: 'Login',
    register: 'Register',
    welcome: 'Welcome Back',
    logout: 'Logout',
    noSubscriptions: 'No subscriptions yet, add one above.',
    confirmDelete: 'Are you sure you want to delete this subscription?',
    language: 'Language',
    accountSecurity: 'Account Security',
    changeUsername: 'Change Username',
    changePassword: 'Change Password',
    newPassword: 'New Password',
    currentPassword: 'Current Password',
    update: 'Update',
    notificationStyle: 'Notification Style',
    simple: 'Simple',
    detailed: 'Detailed',
    defaultNotifyDays: 'Default Reminder (Days)',
    pleaseFillRequired: 'Please fill all required fields (Name, Price, Category)',
    accountCreated: 'Account created, please login',
    userExists: 'Username already exists',
    loginFailed: 'Invalid credentials',
    passwordUpdated: 'Password updated',
    usernameUpdated: 'Username updated',
    uncategorized: 'Uncategorized',
    remaining: 'Remaining',
    dataSync: 'Cloud Sync',
    syncDesc: 'Sync data to cloud database (Supabase)',
    syncNow: 'Sync Now',
    syncSuccess: 'Sync Successful!',
    syncError: 'Sync Failed (Check constants.ts)',
    notConfigured: 'Database not configured',
    baseCurrency: 'Base Currency',
    currencyRatesLabel: 'Exchange Rates',
    refreshRates: 'Refresh Rates',
    lastUpdated: 'Last Updated',
    manualRefresh: 'Refresh Now',
    rateFetchFailed: 'Rate update failed',
    categoryManagement: 'Category Management',
    addCategory: 'Add Category',
    editCategory: 'Edit Category',
    colorPresets: 'Suggested Colors',
    calendarView: 'Subscription Calendar',
    spendingTrends: 'Spending Trends',
    budgetSettings: 'Budget Settings',
    monthlyBudgetLimit: 'Monthly Budget Limit',
    emailNotifications: 'Email Notifications (SMTP)',
    enableEmail: 'Enable Email Notifications',
    smtpServer: 'SMTP Server',
    smtpPort: 'SMTP Port',
    smtpUser: 'SMTP User',
    smtpPassword: 'SMTP Password',
    fromEmail: 'From Email',
    monthlyBudget: 'Monthly Budget',
    spent: 'Spent',
    budgetExceeded: 'You have exceeded your monthly budget!',
    tags: 'Tags (comma separated)',
    chooseIcon: 'Choose Icon',
    tagsPlaceholder: 'e.g. software, work, entertainment',
    budgetDesc: 'Set a monthly spending limit to see alerts on the dashboard when exceeded.',
    chooseColor: 'Choose Color',
    smtpDesc: 'Configure custom SMTP server for email notifications.',
    sendTestEmail: 'Send Test Email',
    emailEnabled: 'Email Notifications Enabled',
    emailDisabled: 'Email Notifications Disabled',
  }
};
